ssh_authorized_keys:
- "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDvlBoH+2ZvOPd74PWgvKIFTYFov8k/plZMjxdgZmChpsQUS5oYZM9k4UOB55n2EDMkZiXpNO08gwGlNUDZWOZ7XZhvU8DCqwXMSf4hG25LElhmhouZ3RgJYQ8cjCD3jQfB+n9QHWScBYvAwJ+iXeti1ZJNGgJm7sD9jS0pL+BCYDTM+ZtgabAe3JSOJUPTpCm/Z+yH4vZE7jfmzgmiyaTqYrQ0/k8qpCFqbIWF5Kyqy/tPf0OVTHfuzXAbj7+RMSpZOed395sTZ/ugRBdwM6tNQWBLQDiSvwUjWf2I0U+h0lixaU7tcihMKDhWo3UHUSuXWMenZ/CU5ThHDDoRDYRrIQOSDiHFU9GFOeBgGEnMYMrw2Tx7FK2oDHSdF3CRIvfEXNpHp24xlX50v7yNOJC0xCFWjkqEdlpD5GujZfq7CyFh7g2ija9K05NJ5sz6HN1B4zl9Kl9Mp/5svjQyhXeXFF8ZcA9cFVw0g/8FSBvTtUyuXdVid7vrPtU0/JWVZVE="
hostname: k3s-1.home

k3os:
  ntp_servers:
  - 0.eu.pool.ntp.org
  - 1.eu.pool.ntp.org
