apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft-pv-world0
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/media/working/cluster/minecraft"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-pvc-world0
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server-world0
  namespace: minecraft
  labels:
    app: minecraft-server
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-server
  template:
    metadata:
      labels:
        app: minecraft-server
    spec:
      hostNetwork: true
      nodeSelector:
        purpose: minecraft
      volumes:
      - name: minecraft-pv-world0
        persistentVolumeClaim:
          claimName: minecraft-pvc-world0
      containers:
      - name: minecraft-server
        image: itzg/minecraft-server:latest
        resources:
          limits:
            memory: 4Gi
          requests:
            memory: 2Gi
        env:
          - name:  EULA
            value: 'TRUE'
          - name: MODE
            value: creative
          - name: MOTD
            value: k3os Minecraft server
          - name: ALLOW_FLIGHT
            value: 'TRUE'
        ports:
        - containerPort: 25565
          name: minecraft
        volumeMounts:
          - name: minecraft-pv-world0
            mountPath:  data
        #readinessProbe:
        #  exec:
        #    command:
        #    - mcstatus
        #    - 127.0.0.1
        #    - ping
        #  initialDelaySeconds: 30
        #  periodSeconds: 30
        #livenessProbe:
        #  exec:
        #    command:
        #    - mcstatus
        #    - 127.0.0.1
        #    - ping
        #  initialDelaySeconds: 30
        #  periodSeconds: 30
